name: "Release"
on:
  workflow_call:
  workflow_dispatch:
defaults:
  run:
    shell: bash
permissions:
  contents: write
  packages: write


jobs:
  build-docker:
    name: Build Docker image
    runs-on: ${{ matrix.runs-on }}
    if: github.ref_name == github.event.repository.default_branch || github.event_name == 'workflow_dispatch'
    env:
      IMAGE_NAME: ${{ github.repository }}

    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runs-on: ubuntu-24.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
          version: latest

      - name: Build and cache image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha,scope=docker-release-${{ matrix.arch }}
          cache-to: type=gha,scope=docker-release-${{ matrix.arch }},mode=max

  release-docker:
    name: "Release Docker image"
    needs:
      - build-docker
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch || github.event_name == 'workflow_dispatch'
    env:
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token}}

      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            type=raw,value=production-latest
            type=sha,format=long

      - name: Build image with labels
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=docker-release-amd64
            type=gha,scope=docker-release-arm64
